## 利用者に対するマッチング指数

### AHPでの最終評価：学生数N=5、企業数M=3の場合

In [25]:
import numpy as np

In [26]:
#学生5人の最終結果(企業数3社)
C = np.array([[0.5, 0.3, 0.2], [0.4, 0.2, 0.4], [0.6, 0.3, 0.1], [0.3, 0.4, 0.3], [0.6, 0.2, 0.2]])
C

array([[0.5, 0.3, 0.2],
       [0.4, 0.2, 0.4],
       [0.6, 0.3, 0.1],
       [0.3, 0.4, 0.3],
       [0.6, 0.2, 0.2]])

In [27]:
#企業3社の最終結果(学生数5人)
S = np.array([[0.2, 0.2, 0.1, 0.3, 0.2],[0.3, 0.2, 0.1, 0.2, 0.2], [0.4, 0.3, 0.1, 0.1, 0.1]])
S.T

array([[0.2, 0.3, 0.4],
       [0.2, 0.2, 0.3],
       [0.1, 0.1, 0.1],
       [0.3, 0.2, 0.1],
       [0.2, 0.2, 0.1]])

In [28]:
#学生の評価項目行列(評価項目数:4)
Sv = np.array([[7, 5, 3, 1], [3, 3, 1, 5], [1, 3, 7, 5], [3, 7, 5, 1], [5, 1, 7, 5]])
Sv

array([[7, 5, 3, 1],
       [3, 3, 1, 5],
       [1, 3, 7, 5],
       [3, 7, 5, 1],
       [5, 1, 7, 5]])

In [29]:
#企業の評価項目行列(評価項目数:4)
Sc = np.array([[5, 5, 3, 1], [3, 1, 1, 5], [3, 3, 7, 5]])
Sc

array([[5, 5, 3, 1],
       [3, 1, 1, 5],
       [3, 3, 7, 5]])

In [30]:
def cos_sim(v1, v2): #コサイン類似度を求める関数
  return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [31]:
L = 4 #評価項目数
R = np.zeros((len(Sv), len(Sc))) #コサイン類似度を格納
for i in range(len(Sv)):
  for j in range(len(Sc)):
    R[i,j] = cos_sim(Sv[i], Sc[j])
R

array([[0.9860133 , 0.61828402, 0.70527442],
       [0.739574  , 0.95478592, 0.78586827],
       [0.6479516 , 0.69102332, 0.97828387],
       [0.92966968, 0.47280543, 0.79627757],
       [0.72295689, 0.8       , 0.9591663 ]])

In [32]:
#マッチング指数を求める
alpha = 1.0
MCG = np.zeros((len(Sv), len(Sc)))
MCG = C * S.T + alpha * R
MCG

array([[1.0860133 , 0.70828402, 0.78527442],
       [0.819574  , 0.99478592, 0.90586827],
       [0.7079516 , 0.72102332, 0.98828387],
       [1.01966968, 0.55280543, 0.82627757],
       [0.84295689, 0.84      , 0.9791663 ]])